/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "CDAP.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rina_messages_objVal_t, rina_messages_objVal_t, 2)


PB_BIND(rina_messages_authPolicy_t, rina_messages_authPolicy_t, AUTO)


PB_BIND(rina_messages_CDAPMessage, rina_messages_CDAPMessage, 2)


PB_BIND(rina_messages_int_t, rina_messages_int_t, AUTO)


PB_BIND(rina_messages_string_t, rina_messages_string_t, AUTO)





