/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "CommonMessages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rina_messages_objectValue_t, rina_messages_objectValue_t, 2)


PB_BIND(rina_messages_nameValuePair_t, rina_messages_nameValuePair_t, 2)


PB_BIND(rina_messages_property_t, rina_messages_property_t, AUTO)


PB_BIND(rina_messages_a_data_t, rina_messages_a_data_t, AUTO)



