/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "ConnectionPoliciesMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rina_messages_dtcpWindowBasedFlowControlConfig_t, rina_messages_dtcpWindowBasedFlowControlConfig_t, AUTO)


PB_BIND(rina_messages_dtcpRateBasedFlowControlConfig_t, rina_messages_dtcpRateBasedFlowControlConfig_t, 2)


PB_BIND(rina_messages_dtcpFlowControlConfig_t, rina_messages_dtcpFlowControlConfig_t, 2)


PB_BIND(rina_messages_dtcpRtxControlConfig_t, rina_messages_dtcpRtxControlConfig_t, 2)


PB_BIND(rina_messages_dtcpConfig_t, rina_messages_dtcpConfig_t, 2)


PB_BIND(rina_messages_dtpConfig_t, rina_messages_dtpConfig_t, 2)


PB_BIND(rina_messages_connection_t, rina_messages_connection_t, 2)



