/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "FlowMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rina_messages_connectionId_t, rina_messages_connectionId_t, AUTO)


PB_BIND(rina_messages_Flow, rina_messages_Flow, 2)



