/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_RINA_MESSAGES_COMMONMESSAGES_PB_H_INCLUDED
#define PB_RINA_MESSAGES_COMMONMESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rina_messages_a_data_t { 
    bool has_sourceAddress;
    int32_t sourceAddress; 
    bool has_destAddress;
    int32_t destAddress; 
    pb_callback_t cdapMessage; 
} rina_messages_a_data_t;

typedef PB_BYTES_ARRAY_T(256) rina_messages_objectValue_t_byteval_t;
typedef struct _rina_messages_objectValue_t { /* value of an object */
    bool has_intval;
    int32_t intval; 
    bool has_sintval;
    int32_t sintval; 
    bool has_int64val;
    int64_t int64val; 
    bool has_sint64val;
    int64_t sint64val; 
    bool has_strval;
    char strval[10]; 
    bool has_byteval;
    rina_messages_objectValue_t_byteval_t byteval; /* arbitrary structure or message */
    bool has_floatval;
    uint32_t floatval; 
    bool has_doubleval;
    uint64_t doubleval; 
} rina_messages_objectValue_t;

typedef struct _rina_messages_property_t { /* carries the information of a name/value pair */
    char name[40]; 
    char value[40]; 
} rina_messages_property_t;

typedef struct _rina_messages_nameValuePair_t { /* A name-value pair */
    bool has_name;
    char name[40]; 
    bool has_value;
    rina_messages_objectValue_t value; 
} rina_messages_nameValuePair_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rina_messages_objectValue_t_init_default {false, 0, false, 0, false, 0, false, 0, false, "", false, {0, {0}}, false, 0, false, 0}
#define rina_messages_nameValuePair_t_init_default {false, "", false, rina_messages_objectValue_t_init_default}
#define rina_messages_property_t_init_default    {"", ""}
#define rina_messages_a_data_t_init_default      {false, 0, false, 0, {{NULL}, NULL}}
#define rina_messages_objectValue_t_init_zero    {false, 0, false, 0, false, 0, false, 0, false, "", false, {0, {0}}, false, 0, false, 0}
#define rina_messages_nameValuePair_t_init_zero  {false, "", false, rina_messages_objectValue_t_init_zero}
#define rina_messages_property_t_init_zero       {"", ""}
#define rina_messages_a_data_t_init_zero         {false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define rina_messages_a_data_t_sourceAddress_tag 1
#define rina_messages_a_data_t_destAddress_tag   2
#define rina_messages_a_data_t_cdapMessage_tag   3
#define rina_messages_objectValue_t_intval_tag   1
#define rina_messages_objectValue_t_sintval_tag  2
#define rina_messages_objectValue_t_int64val_tag 3
#define rina_messages_objectValue_t_sint64val_tag 4
#define rina_messages_objectValue_t_strval_tag   5
#define rina_messages_objectValue_t_byteval_tag  6
#define rina_messages_objectValue_t_floatval_tag 7
#define rina_messages_objectValue_t_doubleval_tag 8
#define rina_messages_property_t_name_tag        1
#define rina_messages_property_t_value_tag       2
#define rina_messages_nameValuePair_t_name_tag   1
#define rina_messages_nameValuePair_t_value_tag  2

/* Struct field encoding specification for nanopb */
#define rina_messages_objectValue_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    intval,            1) \
X(a, STATIC,   OPTIONAL, SINT32,   sintval,           2) \
X(a, STATIC,   OPTIONAL, INT64,    int64val,          3) \
X(a, STATIC,   OPTIONAL, SINT64,   sint64val,         4) \
X(a, STATIC,   OPTIONAL, STRING,   strval,            5) \
X(a, STATIC,   OPTIONAL, BYTES,    byteval,           6) \
X(a, STATIC,   OPTIONAL, FIXED32,  floatval,          7) \
X(a, STATIC,   OPTIONAL, FIXED64,  doubleval,         8)
#define rina_messages_objectValue_t_CALLBACK NULL
#define rina_messages_objectValue_t_DEFAULT NULL

#define rina_messages_nameValuePair_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define rina_messages_nameValuePair_t_CALLBACK NULL
#define rina_messages_nameValuePair_t_DEFAULT NULL
#define rina_messages_nameValuePair_t_value_MSGTYPE rina_messages_objectValue_t

#define rina_messages_property_t_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, STRING,   value,             2)
#define rina_messages_property_t_CALLBACK NULL
#define rina_messages_property_t_DEFAULT NULL

#define rina_messages_a_data_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    sourceAddress,     1) \
X(a, STATIC,   OPTIONAL, INT32,    destAddress,       2) \
X(a, CALLBACK, OPTIONAL, BYTES,    cdapMessage,       3)
#define rina_messages_a_data_t_CALLBACK pb_default_field_callback
#define rina_messages_a_data_t_DEFAULT NULL

extern const pb_msgdesc_t rina_messages_objectValue_t_msg;
extern const pb_msgdesc_t rina_messages_nameValuePair_t_msg;
extern const pb_msgdesc_t rina_messages_property_t_msg;
extern const pb_msgdesc_t rina_messages_a_data_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rina_messages_objectValue_t_fields &rina_messages_objectValue_t_msg
#define rina_messages_nameValuePair_t_fields &rina_messages_nameValuePair_t_msg
#define rina_messages_property_t_fields &rina_messages_property_t_msg
#define rina_messages_a_data_t_fields &rina_messages_a_data_t_msg

/* Maximum encoded size of messages (where known) */
/* rina_messages_a_data_t_size depends on runtime parameters */
#define rina_messages_nameValuePair_t_size       367
#define rina_messages_objectValue_t_size         323
#define rina_messages_property_t_size            82

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
