/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_RINA_MESSAGES_NEIGHBORARRAYMESSAGE_PB_H_INCLUDED
#define PB_RINA_MESSAGES_NEIGHBORARRAYMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "NeighborMessage.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rina_messages_neighbors_t { /* carries information about all the neighbors */
    pb_callback_t neighbor;
} rina_messages_neighbors_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rina_messages_neighbors_t_init_default   {{{NULL}, NULL}}
#define rina_messages_neighbors_t_init_zero      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define rina_messages_neighbors_t_neighbor_tag   1

/* Struct field encoding specification for nanopb */
#define rina_messages_neighbors_t_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  neighbor,          1)
#define rina_messages_neighbors_t_CALLBACK pb_default_field_callback
#define rina_messages_neighbors_t_DEFAULT NULL
#define rina_messages_neighbors_t_neighbor_MSGTYPE rina_messages_neighbor_t

extern const pb_msgdesc_t rina_messages_neighbors_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rina_messages_neighbors_t_fields &rina_messages_neighbors_t_msg

/* Maximum encoded size of messages (where known) */
/* rina_messages_neighbors_t_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
