/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_RINA_MESSAGES_POLICYDESCRIPTORMESSAGE_PB_H_INCLUDED
#define PB_RINA_MESSAGES_POLICYDESCRIPTORMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "CommonMessages.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rina_messages_policyDescriptor_t { /* Describes a policy */
    bool has_policyName;
    char policyName[20]; /* The name of the policy */
    bool has_policyImplName;
    char policyImplName[20]; /* The name of the implementation of the policy used in this DIF. Can be a hierarchical name */
    bool has_version;
    char version[20]; /* The version of the policy implementation */
    pb_callback_t policyParameters; /* The paramters of the policy */
} rina_messages_policyDescriptor_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rina_messages_policyDescriptor_t_init_default {false, "", false, "", false, "", {{NULL}, NULL}}
#define rina_messages_policyDescriptor_t_init_zero {false, "", false, "", false, "", {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define rina_messages_policyDescriptor_t_policyName_tag 1
#define rina_messages_policyDescriptor_t_policyImplName_tag 2
#define rina_messages_policyDescriptor_t_version_tag 3
#define rina_messages_policyDescriptor_t_policyParameters_tag 4

/* Struct field encoding specification for nanopb */
#define rina_messages_policyDescriptor_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   policyName,        1) \
X(a, STATIC,   OPTIONAL, STRING,   policyImplName,    2) \
X(a, STATIC,   OPTIONAL, STRING,   version,           3) \
X(a, CALLBACK, REPEATED, MESSAGE,  policyParameters,   4)
#define rina_messages_policyDescriptor_t_CALLBACK pb_default_field_callback
#define rina_messages_policyDescriptor_t_DEFAULT NULL
#define rina_messages_policyDescriptor_t_policyParameters_MSGTYPE rina_messages_property_t

extern const pb_msgdesc_t rina_messages_policyDescriptor_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rina_messages_policyDescriptor_t_fields &rina_messages_policyDescriptor_t_msg

/* Maximum encoded size of messages (where known) */
/* rina_messages_policyDescriptor_t_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
