macro(rs_scan_cmakelists)
  file(GLOB component_dirs ${CMAKE_SOURCE_DIR}/components/*)
  file(GLOB mock_component_dirs ${CMAKE_SOURCE_DIR}/components_mocks/*)
  list(APPEND component_dirs ${mock_component_dirs})
  foreach(component_dir IN LISTS component_dirs)
    message("Looking in ${component_dir}")
    set(cmakelist "${component_dir}/CMakeLists.txt")
    if(EXISTS ${cmakelist})
      message("Including ${cmakelist}")
      include(${cmakelist})
    endif()
  endforeach()
endmacro()
